"""empty message

Revision ID: 31e68933a2a0
Revises: 7513fb40ab3a
Create Date: 2026-03-24 14:20:35.154800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e68933a2a0'
down_revision: Union[str, Sequence[str], None] = '7513fb40ab3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Enum('OCR', 'DIFY', name='api_provider_enum'), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_logs_provider'), 'api_logs', ['provider'], unique=False)
    op.create_index('ix_api_logs_provider_created_at', 'api_logs', ['provider', 'created_at'], unique=False)
    op.create_index('ix_api_logs_request_id', 'api_logs', ['request_id'], unique=False)
    op.create_index('ix_api_logs_status_code', 'api_logs', ['status_code'], unique=False)
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('API', 'SCRAPER', 'MANUAL', 'TELEGRAM', 'OTHER', name='job_source_type_enum'), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_job_sources_name')
    )
    op.create_index(op.f('ix_job_sources_source_type'), 'job_sources', ['source_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('external_auth_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_auth_id'), 'users', ['external_auth_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('skills_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_jobs_source_external')
    )
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index('ix_jobs_is_active', 'jobs', ['is_active'], unique=False)
    op.create_index('ix_jobs_published_at', 'jobs', ['published_at'], unique=False)
    op.create_index(op.f('ix_jobs_source_id'), 'jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('resume_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_files_user_id'), 'resume_files', ['user_id'], unique=False)
    op.create_table('resume_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_file_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('IMPROVE', 'MATCH', name='session_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'STOPPED', name='session_status_enum'), server_default='QUEUED', nullable=False),
    sa.Column('current_iteration', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_file_id'], ['resume_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_sessions_resume_file_id'), 'resume_sessions', ['resume_file_id'], unique=False)
    op.create_index(op.f('ix_resume_sessions_session_type'), 'resume_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_resume_sessions_status'), 'resume_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_resume_sessions_user_id'), 'resume_sessions', ['user_id'], unique=False)
    op.create_index('ix_resume_sessions_user_status', 'resume_sessions', ['user_id', 'status'], unique=False)
    op.create_index('ix_resume_sessions_user_type', 'resume_sessions', ['user_id', 'session_type'], unique=False)
    op.create_table('resume_text_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('PDF_TEXT', 'OCR', 'IMPROVED', name='resume_source_type_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('structured_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['resume_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'version_no', name='uq_resume_text_versions_session_version')
    )
    op.create_index(op.f('ix_resume_text_versions_session_id'), 'resume_text_versions', ['session_id'], unique=False)
    op.create_index('ix_resume_text_versions_session_source', 'resume_text_versions', ['session_id', 'source_type'], unique=False)
    op.create_index(op.f('ix_resume_text_versions_source_type'), 'resume_text_versions', ['source_type'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('resume_version_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('why_match_json', sa.JSON(), nullable=True),
    sa.Column('gap_skills_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_text_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['resume_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'resume_version_id', 'job_id', name='uq_job_matches_session_version_job')
    )
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_match_score'), 'job_matches', ['match_score'], unique=False)
    op.create_index(op.f('ix_job_matches_resume_version_id'), 'job_matches', ['resume_version_id'], unique=False)
    op.create_index(op.f('ix_job_matches_session_id'), 'job_matches', ['session_id'], unique=False)
    op.create_index('ix_job_matches_session_score', 'job_matches', ['session_id', 'match_score'], unique=False)
    op.create_table('resume_improvement_iterations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('input_version_id', sa.Integer(), nullable=False),
    sa.Column('output_version_id', sa.Integer(), nullable=False),
    sa.Column('dify_response_json', sa.JSON(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['input_version_id'], ['resume_text_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['output_version_id'], ['resume_text_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['resume_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_improvement_iterations_input_version_id'), 'resume_improvement_iterations', ['input_version_id'], unique=False)
    op.create_index(op.f('ix_resume_improvement_iterations_output_version_id'), 'resume_improvement_iterations', ['output_version_id'], unique=False)
    op.create_index('ix_resume_improvement_iterations_session', 'resume_improvement_iterations', ['session_id'], unique=False)
    op.create_index(op.f('ix_resume_improvement_iterations_session_id'), 'resume_improvement_iterations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_improvement_iterations_session_id'), table_name='resume_improvement_iterations')
    op.drop_index('ix_resume_improvement_iterations_session', table_name='resume_improvement_iterations')
    op.drop_index(op.f('ix_resume_improvement_iterations_output_version_id'), table_name='resume_improvement_iterations')
    op.drop_index(op.f('ix_resume_improvement_iterations_input_version_id'), table_name='resume_improvement_iterations')
    op.drop_table('resume_improvement_iterations')
    op.drop_index('ix_job_matches_session_score', table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_session_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_resume_version_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_match_score'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_resume_text_versions_source_type'), table_name='resume_text_versions')
    op.drop_index('ix_resume_text_versions_session_source', table_name='resume_text_versions')
    op.drop_index(op.f('ix_resume_text_versions_session_id'), table_name='resume_text_versions')
    op.drop_table('resume_text_versions')
    op.drop_index('ix_resume_sessions_user_type', table_name='resume_sessions')
    op.drop_index('ix_resume_sessions_user_status', table_name='resume_sessions')
    op.drop_index(op.f('ix_resume_sessions_user_id'), table_name='resume_sessions')
    op.drop_index(op.f('ix_resume_sessions_status'), table_name='resume_sessions')
    op.drop_index(op.f('ix_resume_sessions_session_type'), table_name='resume_sessions')
    op.drop_index(op.f('ix_resume_sessions_resume_file_id'), table_name='resume_sessions')
    op.drop_table('resume_sessions')
    op.drop_index(op.f('ix_resume_files_user_id'), table_name='resume_files')
    op.drop_table('resume_files')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_id'), table_name='jobs')
    op.drop_index('ix_jobs_published_at', table_name='jobs')
    op.drop_index('ix_jobs_is_active', table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_auth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_job_sources_source_type'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index('ix_api_logs_status_code', table_name='api_logs')
    op.drop_index('ix_api_logs_request_id', table_name='api_logs')
    op.drop_index('ix_api_logs_provider_created_at', table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_provider'), table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
